const OrderStatus = {
  ORDER_CREATED: "order_created",
  CANCELLATION_WINDOW: "cancellation_window",
  SELF_CANCELLED: "self_cancelled",
  WINDOW_CLOSED: "window_closed",
  PAYMENT_VERIFIED: "payment_verified",
  ADMIN_PENDING: "admin_pending",
  APPROVED: "approved",
  ADMIN_REJECTED: "admin_rejected",
  PACKING: "packing",
  PACKED: "packed",
  READY_TO_SHIP: "ready_to_ship",
  WITH_CARRIER: "with_carrier",
  OUT_FOR_DELIVERY: "out_for_delivery",
  DELIVERED: "delivered",
  NDR: "ndr",
  RTO: "rto",
  RETURN_WINDOW: "return_window",
  RETURN_REQUESTED: "return_requested",
  RETURN_APPROVED: "return_approved",
  RETURN_REJECTED: "return_rejected",
  RETURN_PICKUP: "return_pickup",
  RETURN_RECEIVED: "return_received",
  QUALITY_CHECK: "quality_check",
  REFUND_PENDING: "REFUND_PENDING",
  REFUND_INITIATED: "REFUND_INITIATED",
  REFUND_PROCESSING: "REFUND_PROCESSING",
  REFUND_COMPLETED: "REFUND_COMPLETED",
  REFUND_FAILED: "REFUND_FAILED",
  COMPLETED: "completed",
  SHIPMENT_FAILED: "shipment_failed",
  FAILED: "failed",

  PENDING: "pending",
  PAID: "paid",
  CANCEL_REQUESTED: "CANCEL_REQUESTED",
  CANCEL_REJECTED: "CANCEL_REJECTED",
  CANCELLED: "cancelled",
};

module.exports = { OrderStatus };
